# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160321_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 17, 4, 8, 397319, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
